management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
    endpoint:
      metrics:
        enabled: true

server:
  error.whitelabel.enabled: false
  servlet:
    context-path: /albeniz


springdoc:
  api-docs:
    path: /api-docs